version: "3"
services:
  chrome:
    image: selenium/standalone-chrome:4.23.0
    shm_size: 2g
    ports:
      - "4444:4444"   # Selenium Grid + UI
      - "7900:7900"   # noVNC to watch browser

  firefox:
    image: selenium/standalone-firefox:4.23.0
    shm_size: 2g
    ports:
      - "4445:4444"   # Selenium Grid + UI
      - "7901:7900"   # noVNC to watch browser
